<?php
    $countyNames = [
        'alba',
        'arges',
        'arad',
        'bacau',
        'bihor',
        'bistrita-nasaud',
        'braila',
        'botosani',
        'bucuresti',
        'brasov',
        'buzau',
        'calarasi',
        'caras-severin',
        'constanta',
        'covasna',
        'dambovita',
        'dolj',
        'gorj',
        'galati',
        'giurgiu',
        'hunedoara',
        'harghita',
        'ilfov',
        'ialomita',
        'iasi',
        'mehedinti',
        'maramures',
        'mures',
        'neamt',
        'olt',
        'prahova',
        'sibiu',
        'salaj',
        'satu mare',
        'suceava',
        'tulcea',
        'timis',
        'teleorman',
        'valcea',
        'vrancea',
        'vaslui',
    ];

    $countyIdToNames = [
        'ab' => 'alba',
        'ag' => 'arges',
        'ar' => 'arad',
        'bc' => 'bacau',
        'bh' => 'bihor',
        'bn' => 'bistrita-nasaud',
        'br' => 'braila',
        'bt' => 'botosani',
        'b' => 'bucuresti',
        'bv' => 'brasov',
        'bz' => 'buzau',
        'cl' => 'calarasi',
        'cs' => 'caras-severin',
        'ct' => 'constanta',
        'cv' => 'covasna',
        'db' => 'dambovita',
        'dj' => 'dolj',
        'gj' => 'gorj',
        'gl' => 'galati',
        'gr' => 'giurgiu',
        'hd' => 'hunedoara',
        'hr' => 'harghita',
        'if' => 'ilfov',
        'il' => 'ialomita',
        'is' => 'iasi',
        'mh' => 'mehedinti',
        'mm' => 'maramures',
        'ms' => 'mures',
        'nt' => 'neamt',
        'ot' => 'olt',
        'ph' => 'prahova',
        'sb' => 'sibiu',
        'sj' => 'salaj',
        'sm' => 'satu mare',
        'sv' => 'suceava',
        'tl' => 'tulcea',
        'tm' => 'timis',
        'tr' => 'teleorman',
        'vl' => 'valcea',
        'vn' => 'vrancea',
        'vs' => 'vaslui',
    ];

?>